# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Eureka'
tagline:          'A Jekyll theme'
description:      'First Lego League team - Austin, Texas'
url:              https://www.teameureka.org
baseurl:          /
dev.baseurl:      /teameureka/

collections:
  fll:
    output: true
    permalink: /fll/:path/

plugins:
  - jekyll-paginate
  - jekyll-gist
  # - jekyll-coffeescript
  # - jekyll-seo-tag
  # - some-other-jekyll-plugin

whitelist:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag

gems:
  - jekyll-gist
  - webrick
  - jekyll-paginate

# Enable safe mode
safe: true
