# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Eureka #51206'
tagline:          'A Jekyll theme'
description:      'First Lego League team from Austin, Texas'
url:              https://www.teameureka.org
baseurl:          /teameureka/


github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  # - jekyll-coffeescript
  # - jekyll-seo-tag
  # - some-other-jekyll-plugin

whitelist:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag

gems:
  - jekyll-gist
  - webrick
  - jekyll-paginate

# Enable safe mode
safe: true
